SELECT `crs`.`crs_id`,
       `crs`.`crs_name`,
       `crs`.`ctu_id`,
       `crs`.`ctu_name`,
       `crs`.`crs_leader`,
       `crs`.`street_address`,
       `crs`.`street_address2`,
       `crs`.`street_address3`,
       `crs`.`street_address4`,
       `crs`.`internal_office_name`,
       `crs`.`city`,
       `crs`.`state`,
       `crs`.`zip_code`,
       `crs`.`country`,
       `crs`.`latitude`,
       `crs`.`longitude`,
       `crs`.`nichd`,
       `crs`.`crs_type`,
       `crs_relative_crs_funded`.`crs_id` AS `crs_relative_crs_funded.crs_id`,
       `crs_relative_crs_funded`.`crs_list` AS `crs_relative_crs_funded.crs_list`,
       `crs_relative_crs_funded`.`crs_name_list` AS `crs_relative_crs_funded.crs_name_list`,
       `crs_relative_crs_unfunded`.`crs_id` AS `crs_relative_crs_unfunded.crs_id`,
       `crs_relative_crs_unfunded`.`crs_list` AS `crs_relative_crs_unfunded.crs_list`,
       `crs_relative_crs_unfunded`.`crs_name_list` AS `crs_relative_crs_unfunded.crs_name_list`,
       `funded_network`.`crs_id` AS `funded_network.crs_id`,
       `funded_network`.`crs_name` AS `funded_network.crs_name`,
       `funded_network`.`network` AS `funded_network.network`,
       `ctu_pi`.`ctu_org_id` AS `ctu_pi.ctu_org_id`,
       `ctu_pi`.`ctu_contact_pi` AS `ctu_pi.ctu_contact_pi`,
       `ctu_pi`.`ctu_pis` AS `ctu_pi.ctu_pis`,
       `ctu_pi`.`ctu_contact_pi_email` AS `ctu_pi.ctu_contact_pi_email`,
       `unfunded_network`.`crs_id` AS `unfunded_network.crs_id`,
       `unfunded_network`.`crs_name` AS `unfunded_network.crs_name`,
       `unfunded_network`.`ctu_id` AS `unfunded_network.ctu_id`,
       `unfunded_network`.`ctu_name` AS `unfunded_network.ctu_name`,
       `unfunded_network`.`leader_name` AS `unfunded_network.leader_name`,
       `unfunded_network`.`network` AS `unfunded_network.network`,
       `crs_ps`.`oty_id` AS `crs_ps.oty_id`,
       `crs_ps`.`crs_id` AS `crs_ps.crs_id`,
       `crs_ps`.`srn_restriction_type` AS `crs_ps.srn_restriction_type`,
       `crs_ps`.`srn_description_text` AS `crs_ps.srn_description_text`,
       `crs_ps`.`oty_type` AS `crs_ps.oty_type`,
       `crs_ps`.`oty_site_category_type` AS `crs_ps.oty_site_category_type`,
       `regulatory`.`id` AS `regulatory.id`,
       `regulatory`.`ctu_name` AS `regulatory.ctu_name`,
       `regulatory`.`associated_regulatory_crs` AS `regulatory.associated_regulatory_crs`,
       `regulatory`.`crs_id` AS `regulatory.crs_id`,
       `regulatory`.`regulatory_authority_name` AS `regulatory.regulatory_authority_name`,
       `regulatory`.`local_irb_ec_name` AS `regulatory.local_irb_ec_name`,
       `regulatory`.`other_irb_ec_name` AS `regulatory.other_irb_ec_name`,
       `regulatory`.`established_ibc` AS `regulatory.established_ibc`,
       `regulatory`.`ibc_name` AS `regulatory.ibc_name`,
       `regulatory`.`language` AS `regulatory.language`,
       `regulatory`.`cti_needed` AS `regulatory.cti_needed`,
       `crs_po`.`crs_id` AS `crs_po.crs_id`,
       `crs_po`.`ctu_id` AS `crs_po.ctu_id`,
       `crs_po`.`po_name` AS `crs_po.po_name`,
       `crs_po`.`email` AS `crs_po.email`,
       `laboratories`.`lab_id` AS `laboratories.lab_id`,
       `laboratories`.`lab_name` AS `laboratories.lab_name`,
       `laboratories`.`location` AS `laboratories.location`,
       `laboratories`.`poc_name` AS `laboratories.poc_name`,
       `laboratories`.`poc_address` AS `laboratories.poc_address`,
       `laboratories`.`certification` AS `laboratories.certification`,
       `laboratories`.`networks` AS `laboratories.networks`,
       `laboratories`.`ldms` AS `laboratories.ldms`,
       `laboratories`.`qa_services` AS `laboratories.qa_services`,
       `laboratories`.`lab_test_performed` AS `laboratories.lab_test_performed`,
       `laboratories`.`certified_by` AS `laboratories.certified_by`,
       `laboratories`.`latitude` AS `laboratories.latitude`,
       `laboratories`.`longtitude` AS `laboratories.longitude`,
       `laboratories->crs_lab`.`crs_lab_id` AS `laboratories.crs_lab.crs_lab_id`,
       `laboratories->crs_lab`.`crs_id` AS `laboratories.crs_lab.crs_id`,
       `laboratories->crs_lab`.`lab_id` AS `laboratories.crs_lab.lab_id`,
       `crs_coordinator`.`crs_id` AS `crs_coordinator.crs_id`,
       `crs_coordinator`.`crs_name` AS `crs_coordinator.crs_name`,
       `crs_coordinator`.`crs_coordinator_name` AS `crs_coordinator.crs_coordinator_name`,
       `crs_coordinator`.`crs_coordinator_mi` AS `crs_coordinator.crs_coordinator_mi`
FROM `crs` AS `crs`
LEFT OUTER JOIN `crs_relative_crs_funded` AS `crs_relative_crs_funded` ON `crs`.`crs_id` = `crs_relative_crs_funded`.`crs_id`
LEFT OUTER JOIN `crs_relative_crs_unfunded` AS `crs_relative_crs_unfunded` ON `crs`.`crs_id` = `crs_relative_crs_unfunded`.`crs_id`
LEFT OUTER JOIN `funded_network` AS `funded_network` ON `crs`.`crs_id` = `funded_network`.`crs_id`
LEFT OUTER JOIN `ctu_pi` AS `ctu_pi` ON `crs`.`ctu_id` = `ctu_pi`.`ctu_org_id`
LEFT OUTER JOIN `unfunded_network` AS `unfunded_network` ON `crs`.`crs_id` = `unfunded_network`.`crs_id`
LEFT OUTER JOIN `crs_ps` AS `crs_ps` ON `crs`.`crs_id` = `crs_ps`.`crs_id`
LEFT OUTER JOIN `regulatory` AS `regulatory` ON `crs`.`crs_id` = `regulatory`.`crs_id`
LEFT OUTER JOIN `crs_po` AS `crs_po` ON `crs`.`crs_id` = `crs_po`.`crs_id`
LEFT OUTER JOIN `crs_lab` AS `laboratories->crs_lab` ON `crs`.`crs_id` = `laboratories->crs_lab`.`crs_id`
LEFT OUTER JOIN `laboratories` AS `laboratories` ON `laboratories`.`lab_id` = `laboratories->crs_lab`.`lab_id`
LEFT OUTER JOIN `crs_coordinator` AS `crs_coordinator` ON `crs`.`crs_id` = `crs_coordinator`.`crs_id`;
